### ISSUE TITLE
aka: throws python traceback on "trace intersect #znc #some-non-existant-channel"

### ISSUE THREAD

**Issue by ghost** [AwwCookies/ZNC-Modules#4]
Running git head/master, commit 17bdfb663b11e66ac08cc8f58ea84b1453e7fea6

So if you run a trace on a channel you have never been in, it throws this interesting error.

```
[2015-10-26 17:23:58.252421] (kindone/freenode) CLI -> ZNC [PRIVMSG *Aka :trace intersect #znc #some-non-existant-channel]
[2015-10-26 17:23:58.252844] (kindone/freenode) ZNC -> CLI [:*Aka!znc@znc.in PRIVMSG kindone :Invalid channel #some-non-existant-channel]
[2015-10-26 17:23:58.253376] modpython: kindone/Aka/OnModCommand failed: Traceback (most recent call last):\x0A  File "/home/kindone/.znc/modules/Aka.py", line 379, in OnModCommand\x0A    self.cmd_trace_intersect(command.split()[2:])\x0A  File "/home/kindone/.znc/modules/Aka.py", line 215, in cmd_trace_intersect\x0A    for user in self.channels[chan]:\x0AKeyError: '#some-non-existant-channel'\x0A
```

**Comment by emagaliff** [comment]
@KindOne- Cannot replicate with sqlite branch. Speak to @AwwCookies for updates to master.

**Comment by emagaliff** [comment]
Cannot replicate on `sqlite`, merged with `master`
